### ISSUE TITLE
微信无法登录

### ISSUE THREAD

**Issue by huijiawanquba** [lianglixin/SandVXposed#30]
你好，我从外部安装了微信到框架，结果报错了：2021-08-14 17:41:52.619 7806-7806/com.tencent.mm E/FirebaseApp: Firebase API initialization failure.
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.firebase.a.a(Unknown Source:71)
        at com.google.firebase.a.zzc(Unknown Source:44)
        at com.google.firebase.a.a(Unknown Source:129)
        at com.google.firebase.a.al(Unknown Source:1000)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:9)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:34)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6540)
        at java.lang.reflect.Method.invoke(Native Method)
        at mirror.RefMethod.call(RefMethod.java:63)
        at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:56)
        at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:497)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:340)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:213)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity2(HCallbackStub.java:207)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleExecuteTransaction(HCallbackStub.java:245)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:96)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
     Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:849)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy24.registerContentObserver(Unknown Source)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1988)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1977)
        at com.google.android.gms.internal.measurement.zzwp.zza(Unknown Source:37)
        at com.google.android.gms.internal.measurement.zzws.zzry(Unknown Source:34)
        at com.google.android.gms.internal.measurement.zzws.get(Unknown Source:13)
        at com.google.android.gms.internal.measurement.zzex.get(Unknown Source:7)
        at com.google.android.gms.internal.measurement.zzfg.zziu(Unknown Source:12)
        at com.google.android.gms.internal.measurement.zzfg.isLoggable(Unknown Source:5)
        at com.google.android.gms.internal.measurement.zzfg.zza(Unknown Source:7)
        at com.google.android.gms.internal.measurement.zzfi.log(Unknown Source:17)
        at com.google.android.gms.internal.measurement.zzgl.<init>(Unknown Source:221)
        at com.google.android.gms.internal.measurement.zzgl.zzg(Unknown Source:33)
        at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source:5)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.google.firebase.a.a(Unknown Source:71) 
        at com.google.firebase.a.zzc(Unknown Source:44) 
        at com.google.firebase.a.a(Unknown Source:129) 
        at com.google.firebase.a.al(Unknown Source:1000) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:9) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:34) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6540) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at mirror.RefMethod.call(RefMethod.java:63) 
        at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:56) 
        at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:497) 
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:340) 
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:213) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity2(HCallbackStub.java:207) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleExecuteTransaction(HCallbackStub.java:245) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:96) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

**Comment by lianglixin** [comment]
试试64位版本

**Comment by huijiawanquba** [comment]
你好，是这样的：我是要同时运行微信和32位的国内版本QQ，所以才用32位框架的。我发现在安装微信到框架的时候，如果不给安装flag为InstallStrategy.DEPEND_SYSTEM_IF_EXIST的话，是不能正常打开微信的。而一旦给了这个flag，卸载框架外部安装的微信，框架里面的微信也会随之卸载，不知道要怎么处理，才能保证外面的卸载不影响里面的，且安装后可以正常使用微信。
